# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yxoJl13VBPsQm_yjxin8PO0v_DSXNC5V
"""

import pandas as pd



#atribuindo o excel a variavel df
df = pd.read_excel(r'/content/drive/MyDrive/Colab Notebooks/projetos/aula1/Vendas.xlsx')

#calculando o faturamento e agrupando o id
faturamento = df[['ID Loja', 'Valor Final']].groupby('ID Loja').sum()

#deixando em forma descrecente
faturamento = faturamento.sort_values(by= 'Valor Final', ascending=False)

#Calculando quantidade
quantidade = df[['ID Loja', 'Quantidade']].groupby('ID Loja').sum()
quantidade = quantidade.sort_values(by ='ID Loja', ascending=False)
#display(quantidade)

#calculando media
media = (faturamento['Valor Final'] / quantidade['Quantidade']).to_frame()
media = media.rename(columns={0:'Media'})
media = media.sort_values(by ='Media', ascending=False)

import smtplib
import email.message


#enviar email
def enviar_email(nome_da_loja, tabela):
  server = smtplib.SMTP('smtp.gmail.com:587')  

  email_content = f'''
  <p>Prezados</p>
  <p> Segue o Relatorio</p>
  {tabela,to_html()}
 '''

  msg = email.message.Message()
  msg['Subject'] = f'Relatorio de Vendas: {nome_da_loja}'
    
  # Fazer antes (apenas na 1ª vez): Ativar Aplicativos não Seguros.
  # Gerenciar Conta Google -> Segurança -> Aplicativos não Seguros -> Habilitar
  # Caso mesmo assim dê o erro: smtplib.SMTPAuthenticationError: (534,
  # Você faz o login no seu e-mail e depois entra em: https://accounts.google.com/DisplayUnlockCaptcha

  msg['From'] = 'bacochinakawai2@gmail.com'
  msg['To'] = 'yourmail@'
  password = "yourpas"
  msg.add_header('Content-Type', 'text/html')
  msg.set_payload(email_content)
    
  s = smtplib.SMTP('smtp.gmail.com: 587')
  s.starttls()
  # Login Credentials for sending the mail
  s.login(msg['From'], password)
  s.sendmail(msg['From'], [msg['To']], msg.as_string().encode('utf-8'))
  print('Email enviado')

lojas = df['ID Loja'].unique()
for loja in lojas:
  tabela_loja = df.loc[df['ID Loja'] == loja, ['ID Loja', 'Quantidade', 'Valor Final']]
  resumo_loja = tabela_loja.groupby('ID Loja').sum()
  resumo_loja['Media'] = resumo_loja['Valor Final'] / resumo_loja['Quantidade']
  enviar_email(resumo_loja, loja)
